version: '3'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 20s
      retries: 10
  work-queue:
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_QUEUE=redis
  web-controller:
    build:
      context: web_controller
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '5000:5000'