version: '3'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 20s
      retries: 10
  worker:
    build:
      context: worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_QUEUE=redis
  queue-wrapper:
    build:
      context: queue-wrapper
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '7777:5000'